"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _DogTrick:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DogTrickEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DogTrick.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DOG_TRICK_UNSPECIFIED: _DogTrick.ValueType  # 0
    DOG_TRICK_LAY_DOWN: _DogTrick.ValueType  # 1
    DOG_TRICK_ROLL_OVER: _DogTrick.ValueType  # 2
    DOG_TRICK_SIT: _DogTrick.ValueType  # 3
    DOG_TRICK_SHAKE: _DogTrick.ValueType  # 4
    DOG_TRICK_HIGH_FIVE: _DogTrick.ValueType  # 5
    DOG_TRICK_GO_TO_BED: _DogTrick.ValueType  # 6
    DOG_TRICK_STAY: _DogTrick.ValueType  # 7
    DOG_TRICK_COME: _DogTrick.ValueType  # 8
    DOG_TRICK_FETCH: _DogTrick.ValueType  # 9
    DOG_TRICK_GO_TO_SPOT: _DogTrick.ValueType  # 10
    DOG_TRICK_BUTTON: _DogTrick.ValueType  # 11
    DOG_TRICK_LETS_GO: _DogTrick.ValueType  # 12
    DOG_TRICK_THIS_WAY: _DogTrick.ValueType  # 13
    DOG_TRICK_LEAVE_IT: _DogTrick.ValueType  # 14
    DOG_TRICK_DROP_IT: _DogTrick.ValueType  # 15

class DogTrick(_DogTrick, metaclass=_DogTrickEnumTypeWrapper): ...

DOG_TRICK_UNSPECIFIED: DogTrick.ValueType  # 0
DOG_TRICK_LAY_DOWN: DogTrick.ValueType  # 1
DOG_TRICK_ROLL_OVER: DogTrick.ValueType  # 2
DOG_TRICK_SIT: DogTrick.ValueType  # 3
DOG_TRICK_SHAKE: DogTrick.ValueType  # 4
DOG_TRICK_HIGH_FIVE: DogTrick.ValueType  # 5
DOG_TRICK_GO_TO_BED: DogTrick.ValueType  # 6
DOG_TRICK_STAY: DogTrick.ValueType  # 7
DOG_TRICK_COME: DogTrick.ValueType  # 8
DOG_TRICK_FETCH: DogTrick.ValueType  # 9
DOG_TRICK_GO_TO_SPOT: DogTrick.ValueType  # 10
DOG_TRICK_BUTTON: DogTrick.ValueType  # 11
DOG_TRICK_LETS_GO: DogTrick.ValueType  # 12
DOG_TRICK_THIS_WAY: DogTrick.ValueType  # 13
DOG_TRICK_LEAVE_IT: DogTrick.ValueType  # 14
DOG_TRICK_DROP_IT: DogTrick.ValueType  # 15
global___DogTrick = DogTrick

class _DogBehavior:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _DogBehaviorEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_DogBehavior.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    DOG_BEHAVIOR_UNSPECIFIED: _DogBehavior.ValueType  # 0
    DOG_BEHAVIOR_WAGGING_TAIL: _DogBehavior.ValueType  # 1
    DOG_BEHAVIOR_PUPPY_EYES: _DogBehavior.ValueType  # 2
    DOG_BEHAVIOR_HEAD_TILT: _DogBehavior.ValueType  # 3
    DOG_BEHAVIOR_SNEEZE: _DogBehavior.ValueType  # 4
    DOG_BEHAVIOR_YAWN: _DogBehavior.ValueType  # 5
    DOG_BEHAVIOR_BARK: _DogBehavior.ValueType  # 6
    DOG_BEHAVIOR_PANT: _DogBehavior.ValueType  # 10
    DOG_BEHAVIOR_LICK: _DogBehavior.ValueType  # 11
    DOG_BEHAVIOR_JUMP: _DogBehavior.ValueType  # 12
    DOG_BEHAVIOR_SPIN: _DogBehavior.ValueType  # 13
    DOG_BEHAVIOR_SAD_PUPPY_EYES: _DogBehavior.ValueType  # 14
    DOG_BEHAVIOR_SLEEPY: _DogBehavior.ValueType  # 15
    DOG_BEHAVIOR_MAKE_BED: _DogBehavior.ValueType  # 16
    DOG_BEHAVIOR_CARRY_TOY: _DogBehavior.ValueType  # 17
    DOG_BEHAVIOR_CHOMP: _DogBehavior.ValueType  # 18
    DOG_BEHAVIOR_TUG_OF_WAR: _DogBehavior.ValueType  # 19

class DogBehavior(_DogBehavior, metaclass=_DogBehaviorEnumTypeWrapper): ...

DOG_BEHAVIOR_UNSPECIFIED: DogBehavior.ValueType  # 0
DOG_BEHAVIOR_WAGGING_TAIL: DogBehavior.ValueType  # 1
DOG_BEHAVIOR_PUPPY_EYES: DogBehavior.ValueType  # 2
DOG_BEHAVIOR_HEAD_TILT: DogBehavior.ValueType  # 3
DOG_BEHAVIOR_SNEEZE: DogBehavior.ValueType  # 4
DOG_BEHAVIOR_YAWN: DogBehavior.ValueType  # 5
DOG_BEHAVIOR_BARK: DogBehavior.ValueType  # 6
DOG_BEHAVIOR_PANT: DogBehavior.ValueType  # 10
DOG_BEHAVIOR_LICK: DogBehavior.ValueType  # 11
DOG_BEHAVIOR_JUMP: DogBehavior.ValueType  # 12
DOG_BEHAVIOR_SPIN: DogBehavior.ValueType  # 13
DOG_BEHAVIOR_SAD_PUPPY_EYES: DogBehavior.ValueType  # 14
DOG_BEHAVIOR_SLEEPY: DogBehavior.ValueType  # 15
DOG_BEHAVIOR_MAKE_BED: DogBehavior.ValueType  # 16
DOG_BEHAVIOR_CARRY_TOY: DogBehavior.ValueType  # 17
DOG_BEHAVIOR_CHOMP: DogBehavior.ValueType  # 18
DOG_BEHAVIOR_TUG_OF_WAR: DogBehavior.ValueType  # 19
global___DogBehavior = DogBehavior

class _Status:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _StatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Status.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    STATUS_UNSPECIFIED: _Status.ValueType  # 0
    STATUS_SUCCESS: _Status.ValueType  # 1
    STATUS_ERROR: _Status.ValueType  # 2

class Status(_Status, metaclass=_StatusEnumTypeWrapper): ...

STATUS_UNSPECIFIED: Status.ValueType  # 0
STATUS_SUCCESS: Status.ValueType  # 1
STATUS_ERROR: Status.ValueType  # 2
global___Status = Status

class _Location:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _LocationEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_Location.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    LOCATION_UNSPECIFIED: _Location.ValueType  # 0
    LOCATION_OUTSIDE: _Location.ValueType  # 1
    LOCATION_LOTS_OF_DOGS: _Location.ValueType  # 2
    LOCATION_DOG_PARK: _Location.ValueType  # 3
    LOCATION_SQUIRRELS_PRESENT: _Location.ValueType  # 4
    LOCATION_HOME: _Location.ValueType  # 5
    LOCATION_TASTY_TREATS: _Location.ValueType  # 6
    LOCATION_PET_STORE: _Location.ValueType  # 7
    LOCATION_INSIDE: _Location.ValueType  # 8

class Location(_Location, metaclass=_LocationEnumTypeWrapper): ...

LOCATION_UNSPECIFIED: Location.ValueType  # 0
LOCATION_OUTSIDE: Location.ValueType  # 1
LOCATION_LOTS_OF_DOGS: Location.ValueType  # 2
LOCATION_DOG_PARK: Location.ValueType  # 3
LOCATION_SQUIRRELS_PRESENT: Location.ValueType  # 4
LOCATION_HOME: Location.ValueType  # 5
LOCATION_TASTY_TREATS: Location.ValueType  # 6
LOCATION_PET_STORE: Location.ValueType  # 7
LOCATION_INSIDE: Location.ValueType  # 8
global___Location = Location

@typing.final
class GetDogTreatPriceRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOG_NAME_FIELD_NUMBER: builtins.int
    DOG_TREAT_TO_BELLY_RUB_RATIO_FIELD_NUMBER: builtins.int
    TRICKS_TO_PERFORM_FIELD_NUMBER: builtins.int
    CUTES_TO_INCLUDE_FIELD_NUMBER: builtins.int
    LOCATION_FIELD_NUMBER: builtins.int
    dog_name: builtins.str
    dog_treat_to_belly_rub_ratio: builtins.float
    location: global___Location.ValueType
    @property
    def tricks_to_perform(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___DogTrick.ValueType]: ...
    @property
    def cutes_to_include(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[global___DogBehavior.ValueType]: ...
    def __init__(
        self,
        *,
        dog_name: builtins.str = ...,
        dog_treat_to_belly_rub_ratio: builtins.float = ...,
        tricks_to_perform: collections.abc.Iterable[global___DogTrick.ValueType] | None = ...,
        cutes_to_include: collections.abc.Iterable[global___DogBehavior.ValueType] | None = ...,
        location: global___Location.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["cutes_to_include", b"cutes_to_include", "dog_name", b"dog_name", "dog_treat_to_belly_rub_ratio", b"dog_treat_to_belly_rub_ratio", "location", b"location", "tricks_to_perform", b"tricks_to_perform"]) -> None: ...

global___GetDogTreatPriceRequest = GetDogTreatPriceRequest

@typing.final
class GetDogTreatPriceResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRICING_RESULT_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    error: builtins.str
    status: global___Status.ValueType
    @property
    def pricing_result(self) -> global___PricingResult: ...
    def __init__(
        self,
        *,
        pricing_result: global___PricingResult | None = ...,
        error: builtins.str = ...,
        status: global___Status.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["error", b"error", "pricing_result", b"pricing_result", "result", b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["error", b"error", "pricing_result", b"pricing_result", "result", b"result", "status", b"status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["result", b"result"]) -> typing.Literal["pricing_result", "error"] | None: ...

global___GetDogTreatPriceResponse = GetDogTreatPriceResponse

@typing.final
class PerformDogTrickRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DOG_NAME_FIELD_NUMBER: builtins.int
    PRICING_ID_FIELD_NUMBER: builtins.int
    dog_name: builtins.str
    pricing_id: builtins.str
    def __init__(
        self,
        *,
        dog_name: builtins.str = ...,
        pricing_id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["dog_name", b"dog_name", "pricing_id", b"pricing_id"]) -> None: ...

global___PerformDogTrickRequest = PerformDogTrickRequest

@typing.final
class PerformDogTrickResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CURRENT_TRICK_FIELD_NUMBER: builtins.int
    ERROR_MESSAGE_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    DOG_NAME_FIELD_NUMBER: builtins.int
    PRICING_ID_FIELD_NUMBER: builtins.int
    error_message: builtins.str
    status: global___Status.ValueType
    dog_name: builtins.str
    pricing_id: builtins.str
    @property
    def current_trick(self) -> global___CurrentTrick: ...
    def __init__(
        self,
        *,
        current_trick: global___CurrentTrick | None = ...,
        error_message: builtins.str = ...,
        status: global___Status.ValueType = ...,
        dog_name: builtins.str = ...,
        pricing_id: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["current_trick", b"current_trick", "error_message", b"error_message", "result", b"result"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["current_trick", b"current_trick", "dog_name", b"dog_name", "error_message", b"error_message", "pricing_id", b"pricing_id", "result", b"result", "status", b"status"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["result", b"result"]) -> typing.Literal["current_trick", "error_message"] | None: ...

global___PerformDogTrickResponse = PerformDogTrickResponse

@typing.final
class CurrentTrick(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRICK_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    TRICK_DESCRIPTION_FIELD_NUMBER: builtins.int
    trick: global___DogTrick.ValueType
    status: global___Status.ValueType
    trick_description: builtins.str
    def __init__(
        self,
        *,
        trick: global___DogTrick.ValueType = ...,
        status: global___Status.ValueType = ...,
        trick_description: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status", "trick", b"trick", "trick_description", b"trick_description"]) -> None: ...

global___CurrentTrick = CurrentTrick

@typing.final
class PricingResult(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRICING_ID_FIELD_NUMBER: builtins.int
    DOG_TREAT_PRICE_FIELD_NUMBER: builtins.int
    BELLY_RUB_PRICE_FIELD_NUMBER: builtins.int
    REQUEST_FIELD_NUMBER: builtins.int
    pricing_id: builtins.str
    dog_treat_price: builtins.float
    belly_rub_price: builtins.float
    @property
    def request(self) -> global___GetDogTreatPriceRequest: ...
    def __init__(
        self,
        *,
        pricing_id: builtins.str = ...,
        dog_treat_price: builtins.float = ...,
        belly_rub_price: builtins.float = ...,
        request: global___GetDogTreatPriceRequest | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["request", b"request"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["belly_rub_price", b"belly_rub_price", "dog_treat_price", b"dog_treat_price", "pricing_id", b"pricing_id", "request", b"request"]) -> None: ...

global___PricingResult = PricingResult

@typing.final
class HealthCheckResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SERVICE_NAME_FIELD_NUMBER: builtins.int
    VERSION_FIELD_NUMBER: builtins.int
    service_name: builtins.str
    version: builtins.str
    def __init__(
        self,
        *,
        service_name: builtins.str = ...,
        version: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["service_name", b"service_name", "version", b"version"]) -> None: ...

global___HealthCheckResponse = HealthCheckResponse
