# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from grpc_service.v1 import service_pb2 as grpc__service_dot_v1_dot_service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in grpc_service/v1/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DogTrickServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDogTreatPrice = channel.unary_unary(
                '/backend.grpc_service.v1.DogTrickService/GetDogTreatPrice',
                request_serializer=grpc__service_dot_v1_dot_service__pb2.GetDogTreatPriceRequest.SerializeToString,
                response_deserializer=grpc__service_dot_v1_dot_service__pb2.GetDogTreatPriceResponse.FromString,
                _registered_method=True)
        self.PerformDogTrick = channel.unary_stream(
                '/backend.grpc_service.v1.DogTrickService/PerformDogTrick',
                request_serializer=grpc__service_dot_v1_dot_service__pb2.PerformDogTrickRequest.SerializeToString,
                response_deserializer=grpc__service_dot_v1_dot_service__pb2.PerformDogTrickResponse.FromString,
                _registered_method=True)
        self.HeathCheck = channel.unary_unary(
                '/backend.grpc_service.v1.DogTrickService/HeathCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=grpc__service_dot_v1_dot_service__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class DogTrickServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDogTreatPrice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PerformDogTrick(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HeathCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DogTrickServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDogTreatPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDogTreatPrice,
                    request_deserializer=grpc__service_dot_v1_dot_service__pb2.GetDogTreatPriceRequest.FromString,
                    response_serializer=grpc__service_dot_v1_dot_service__pb2.GetDogTreatPriceResponse.SerializeToString,
            ),
            'PerformDogTrick': grpc.unary_stream_rpc_method_handler(
                    servicer.PerformDogTrick,
                    request_deserializer=grpc__service_dot_v1_dot_service__pb2.PerformDogTrickRequest.FromString,
                    response_serializer=grpc__service_dot_v1_dot_service__pb2.PerformDogTrickResponse.SerializeToString,
            ),
            'HeathCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HeathCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=grpc__service_dot_v1_dot_service__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'backend.grpc_service.v1.DogTrickService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('backend.grpc_service.v1.DogTrickService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DogTrickService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDogTreatPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/backend.grpc_service.v1.DogTrickService/GetDogTreatPrice',
            grpc__service_dot_v1_dot_service__pb2.GetDogTreatPriceRequest.SerializeToString,
            grpc__service_dot_v1_dot_service__pb2.GetDogTreatPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PerformDogTrick(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/backend.grpc_service.v1.DogTrickService/PerformDogTrick',
            grpc__service_dot_v1_dot_service__pb2.PerformDogTrickRequest.SerializeToString,
            grpc__service_dot_v1_dot_service__pb2.PerformDogTrickResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HeathCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/backend.grpc_service.v1.DogTrickService/HeathCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            grpc__service_dot_v1_dot_service__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
